# SITE SETTINGS
title: BirdCast

# SOCIAL PROFILES
# None set

# THEME SETTINGS
theme: minima # Fallback theme
remote_theme: peterdesmet/petridish@3.1
pages_on_home: # Custom attribute for _layouts/home.html
  - title: Visualize # External page
    background: /assets/backgrounds/visualize.png
    url: https://iskandari.github.io
    baseurl: /birdcast.org
  - title: Browse # Internal page, see pages/browse.md
    background: /assets/backgrounds/browse.jpg
    url: /browse/
github_edit: true
colors:
  links: "#295cc9"
  banner: "#282949"
  footer: "#0d1626"
font_serif: false

# BUILD SETTINGS
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - LICENSE

# FRONTMATTER DEFAULTS
# None set
